services:
    tmdb_api_client:
        class:        bogdanfinn\tmdbBundle\Http\TmdbClient
        arguments:    ["%api_key%"]
    tmdb_tvshow_client:
        class:        bogdanfinn\tmdbBundle\Http\TMDb\TvShowClient
        arguments:    ["@tmdb_api_client"]
    tmdb_movie_client:
        class:        bogdanfinn\tmdbBundle\Http\TMDb\MovieClient
        arguments:    ["@tmdb_api_client"]
    tmdb_series_transformer:
        class:        bogdanfinn\tmdbBundle\Conversion\SeriesTransformer
        arguments:    []
    tmdb_movie_transformer:
        class:        bogdanfinn\tmdbBundle\Conversion\MovieTransformer
        arguments:    []
    tmdb_twig_image_extension:
        class:        bogdanfinn\tmdbBundle\Twig\TmdbExtension
        arguments:    []