services:
    tmdb_api_client:
        class:        bogdanfinn\TmdbBundle\Http\TmdbClient
        arguments:    ["%tmdb.api_key%"]
    tmdb_tvshow_transformer:
        class:        bogdanfinn\TmdbBundle\Conversion\TvShowTransformer
        arguments:    []
    tmdb_movie_transformer:
        class:        bogdanfinn\TmdbBundle\Conversion\MovieTransformer
        arguments:    []
    tmdb_episode_transformer:
        class:        bogdanfinn\TmdbBundle\Conversion\EpisodeTransformer
        arguments:    []
    tmdb_season_transformer:
        class:        bogdanfinn\TmdbBundle\Conversion\SeasonTransformer
        arguments:    []
    tmdb_search_transformer:
        class:        bogdanfinn\TmdbBundle\Conversion\SearchTransformer
        arguments:    []
    tmdb_tvshow_client:
        class:        bogdanfinn\TmdbBundle\Http\TvShowClient
        arguments:    ["@tmdb_api_client", "@tmdb_tvshow_transformer", "%tmdb.use_models%", "@tmdb_search_client"]
    tmdb_movie_client:
        class:        bogdanfinn\TmdbBundle\Http\MovieClient
        arguments:    ["@tmdb_api_client", "@tmdb_movie_transformer", "%tmdb.use_models%", "@tmdb_search_client"]
    tmdb_season_client:
        class:        bogdanfinn\TmdbBundle\Http\SeasonClient
        arguments:    ["@tmdb_api_client", "@tmdb_season_transformer", "%tmdb.use_models%"]
    tmdb_episode_client:
        class:        bogdanfinn\TmdbBundle\Http\EpisodeClient
        arguments:    ["@tmdb_api_client", "@tmdb_episode_transformer", "%tmdb.use_models%"]
    tmdb_search_client:
        class:        bogdanfinn\TmdbBundle\Http\SearchClient
        arguments:    ["@tmdb_api_client", "@tmdb_movie_transformer","@tmdb_tvshow_transformer","@tmdb_season_transformer", "@tmdb_episode_transformer", "@tmdb_search_transformer", "%tmdb.use_models%"]
    tmdb_twig_image_extension:
        class:        bogdanfinn\TmdbBundle\Twig\TmdbExtension
        arguments:    []